apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: sample:v1
          ports:
            - name: http-server
              containerPort: 80
          imagePullPolicy: Never
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 3
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: sample:v2
          ports:
            - name: http-server
              containerPort: 80
          imagePullPolicy: Never
